#!/bin/python3


#
# Complete the 'sockMerchant' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY ar
#


def sockMerchant(n, ar):
    # Write your code here
    pair_count = 0
    sock_colors = set(ar)
    for i in sock_colors:
        pair_count += ar.count(i) // 2
    return pair_count
    
    
n = int(input())
ar = list(map(int, input().split()))

print(sockMerchant(n, ar))
